CREATE TABLE IF NOT EXISTS WORDS (
	WORD_ID 	INTEGER PRIMARY KEY,
	WORD		TEXT UNIQUE NOT NULL,
	FREQUENCY	INTEGER NOT NULL DEFAULT 0 CHECK(FREQUENCY>=0),
	SOURCE		TEXT NOT NULL,
	CREATED_TS	TEXT NOT NULL,
	UPDATED_TS	TEXT DEFAULT NULL,
	DELETED_TS	TEXT DEFAULT NULL
);

SELECT * FROM WORDS;
